-- ==========================================
-- APLIKASI QASIR - SUPABASE DATABASE SCHEMA
-- PRODUCTION READY - SECURE RLS & REALTIME SYNC
-- ==========================================

-- Enable UUID extension if needed
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==========================================
-- 0. PROFILES TABLE (Role-Based Access)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    email TEXT NOT NULL,
    full_name TEXT NOT NULL DEFAULT 'Kasir',
    role TEXT NOT NULL DEFAULT 'kasir' CHECK (role IN ('owner', 'kasir')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Auto-create profile on user signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
    user_count INT;
    assigned_role TEXT;
BEGIN
    -- Count existing profiles to determine role
    SELECT COUNT(*) INTO user_count FROM public.profiles;
    
    -- First user becomes owner, subsequent users are kasir
    IF user_count = 0 THEN
        assigned_role := 'owner';
    ELSE
        assigned_role := 'kasir';
    END IF;

    INSERT INTO public.profiles (id, email, full_name, role)
    VALUES (
        NEW.id,
        NEW.email,
        COALESCE(NEW.raw_user_meta_data->>'full_name', 'Kasir'),
        assigned_role
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Drop trigger if exists, then create
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ==========================================
-- 1. CATEGORIES TABLE
-- ==========================================
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    icon VARCHAR(50) DEFAULT 'ShoppingBag',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 2. PRODUCTS TABLE
-- ==========================================
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(100) NOT NULL,
    buy_price NUMERIC(12, 2) NOT NULL DEFAULT 0,
    sell_price NUMERIC(12, 2) NOT NULL DEFAULT 0,
    stock INT NOT NULL DEFAULT 0,
    min_stock INT NOT NULL DEFAULT 5,
    unit VARCHAR(50) DEFAULT 'pcs',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Set REPLICA IDENTITY FULL so DELETE events include old record fields
ALTER TABLE public.products REPLICA IDENTITY FULL;
ALTER TABLE public.categories REPLICA IDENTITY FULL;
ALTER TABLE public.transactions REPLICA IDENTITY FULL;

-- ==========================================
-- 3. TRANSACTIONS TABLE (with user_id audit)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_no VARCHAR(50) NOT NULL UNIQUE,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    subtotal NUMERIC(12, 2) NOT NULL DEFAULT 0,
    discount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    tax NUMERIC(12, 2) NOT NULL DEFAULT 0,
    total NUMERIC(12, 2) NOT NULL DEFAULT 0,
    pay_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    change_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    payment_method VARCHAR(50) NOT NULL DEFAULT 'Tunai',
    status VARCHAR(20) NOT NULL DEFAULT 'SELESAI',
    sync_status VARCHAR(20) NOT NULL DEFAULT 'TERSYNC',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 4. TRANSACTION ITEMS TABLE
-- ==========================================
CREATE TABLE IF NOT EXISTS public.transaction_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT REFERENCES public.transactions(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    sku VARCHAR(50),
    name VARCHAR(255) NOT NULL,
    buy_price NUMERIC(12, 2) NOT NULL DEFAULT 0,
    sell_price NUMERIC(12, 2) NOT NULL DEFAULT 0,
    qty INT NOT NULL DEFAULT 1,
    subtotal NUMERIC(12, 2) NOT NULL DEFAULT 0
);

-- ==========================================
-- 5. SETTINGS TABLE
-- ==========================================
CREATE TABLE IF NOT EXISTS public.settings (
    key VARCHAR(100) PRIMARY KEY,
    value TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- INDEXES FOR PERFORMANCE
-- ==========================================
CREATE INDEX IF NOT EXISTS idx_products_sku ON public.products(sku);
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products(category);
CREATE INDEX IF NOT EXISTS idx_transactions_receipt_no ON public.transactions(receipt_no);
CREATE INDEX IF NOT EXISTS idx_transactions_date ON public.transactions(date);
CREATE INDEX IF NOT EXISTS idx_transactions_user_id ON public.transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_transaction_items_tx_id ON public.transaction_items(transaction_id);
CREATE INDEX IF NOT EXISTS idx_profiles_role ON public.profiles(role);

-- ==========================================
-- TRIGGER FOR UPDATED_AT ON PRODUCTS
-- ==========================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_products_updated_at ON public.products;
CREATE TRIGGER trigger_products_updated_at
    BEFORE UPDATE ON public.products
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ==========================================
-- HELPER: Check if user is owner
-- ==========================================
CREATE OR REPLACE FUNCTION public.is_owner()
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM public.profiles
        WHERE id = auth.uid() AND role = 'owner'
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ==========================================
-- ENABLE ROW LEVEL SECURITY (RLS)
-- ==========================================
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transaction_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- RLS POLICIES — PROFILES
-- ==========================================
CREATE POLICY "Authenticated users can view profiles"
    ON public.profiles FOR SELECT
    USING (auth.uid() IS NOT NULL);

CREATE POLICY "Users can update own profile"
    ON public.profiles FOR UPDATE
    USING (auth.uid() = id)
    WITH CHECK (auth.uid() = id);

CREATE POLICY "Owner can manage all profiles"
    ON public.profiles FOR ALL
    USING (public.is_owner());

-- ==========================================
-- RLS POLICIES — CATEGORIES
-- ==========================================
CREATE POLICY "Authenticated select categories"
    ON public.categories FOR SELECT
    USING (auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated insert categories"
    ON public.categories FOR INSERT
    WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated update categories"
    ON public.categories FOR UPDATE
    USING (auth.uid() IS NOT NULL);

CREATE POLICY "Owner delete categories"
    ON public.categories FOR DELETE
    USING (public.is_owner());

-- ==========================================
-- RLS POLICIES — PRODUCTS
-- ==========================================
CREATE POLICY "Authenticated select products"
    ON public.products FOR SELECT
    USING (auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated insert products"
    ON public.products FOR INSERT
    WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated update products"
    ON public.products FOR UPDATE
    USING (auth.uid() IS NOT NULL);

CREATE POLICY "Owner delete products"
    ON public.products FOR DELETE
    USING (public.is_owner());

-- ==========================================
-- RLS POLICIES — TRANSACTIONS
-- ==========================================
CREATE POLICY "Authenticated select transactions"
    ON public.transactions FOR SELECT
    USING (auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated insert transactions"
    ON public.transactions FOR INSERT
    WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated update transactions"
    ON public.transactions FOR UPDATE
    USING (auth.uid() IS NOT NULL);

CREATE POLICY "Owner delete transactions"
    ON public.transactions FOR DELETE
    USING (public.is_owner());

-- ==========================================
-- RLS POLICIES — TRANSACTION ITEMS
-- ==========================================
CREATE POLICY "Authenticated select transaction_items"
    ON public.transaction_items FOR SELECT
    USING (auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated insert transaction_items"
    ON public.transaction_items FOR INSERT
    WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated update transaction_items"
    ON public.transaction_items FOR UPDATE
    USING (auth.uid() IS NOT NULL);

CREATE POLICY "Owner delete transaction_items"
    ON public.transaction_items FOR DELETE
    USING (public.is_owner());

-- ==========================================
-- RLS POLICIES — SETTINGS
-- ==========================================
CREATE POLICY "Authenticated select settings"
    ON public.settings FOR SELECT
    USING (auth.uid() IS NOT NULL);

CREATE POLICY "Owner insert settings"
    ON public.settings FOR INSERT
    WITH CHECK (public.is_owner());

CREATE POLICY "Owner update settings"
    ON public.settings FOR UPDATE
    USING (public.is_owner());

-- ==========================================
-- ENABLE REALTIME ON TABLES
-- ==========================================
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'products'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.products;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'categories'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.categories;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'transactions'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.transactions;
  END IF;
END $$;

-- ==========================================
-- SEED INITIAL DATA
-- ==========================================
INSERT INTO public.categories (id, name, icon) VALUES
(1, 'Sembako & Bumbu', 'ShoppingBag'),
(2, 'Minuman', 'Coffee'),
(3, 'Makanan Ringan', 'Utensils'),
(4, 'Perawatan & Mandi', 'Smile'),
(5, 'Kebutuhan Rumah', 'Home'),
(6, 'Alat Tulis', 'BookOpen')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.products (sku, name, category, buy_price, sell_price, stock, min_stock, unit) VALUES
('899999900001', 'Minyak Goreng Sania 2 Litur', 'Sembako & Bumbu', 32000, 36500, 45, 10, 'pouch'),
('899999900002', 'Beras Pandan Wangi 5kg', 'Sembako & Bumbu', 68000, 76000, 20, 5, 'karung'),
('899100100003', 'Gula Pasir Gulaku 1kg', 'Sembako & Bumbu', 15000, 17500, 35, 8, 'bungkus'),
('899200200004', 'Teh Botol Sosro 450ml', 'Minuman', 4000, 6000, 60, 15, 'botol'),
('899300300005', 'Kopi Kapal Api Grande 20g', 'Minuman', 1500, 2500, 120, 20, 'sachet'),
('899400400006', 'Air Mineral Le Minerale 600ml', 'Minuman', 2500, 4000, 80, 24, 'botol'),
('899500500007', 'Indomie Goreng Spesial 85g', 'Makanan Ringan', 2800, 3500, 150, 30, 'bungkus'),
('899600600008', 'Chitato Sapi Panggang 68g', 'Makanan Ringan', 9500, 12000, 4, 10, 'bungkus'),
('899700700009', 'Sabun Lifebuoy Total 10 110g', 'Perawatan & Mandi', 4200, 5500, 40, 10, 'pcs'),
('899800800010', 'Shampoo Pantene Hair Fall 160ml', 'Perawatan & Mandi', 22000, 26500, 18, 5, 'botol'),
('899900900011', 'Deterjen Rinso Anti Noda 770g', 'Kebutuhan Rumah', 19500, 23500, 25, 6, 'pouch'),
('899111100012', 'Pembersih Lantai Super Pell 770ml', 'Kebutuhan Rumah', 13500, 16500, 2, 5, 'pouch')
ON CONFLICT (sku) DO NOTHING;

INSERT INTO public.settings (key, value) VALUES
('storeName', 'Toko Berkah Utama'),
('storeAddress', 'Jl. Raya Merdeka No. 88, Jakarta Selatan'),
('storePhone', '0812-3456-7890'),
('receiptFooter', 'Terima Kasih Atas Kunjungan Anda! Barang yang sudah dibeli tidak dapat ditukar/dikembalikan.'),
('taxRate', '0'),
('enableAutoSync', 'true'),
('theme', 'dark')
ON CONFLICT (key) DO NOTHING;
