-- Migration: 20260704000000_init_pos_schema.sql

-- 1. CATEGORIES TABLE
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    icon VARCHAR(50) DEFAULT 'ShoppingBag',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. PRODUCTS TABLE
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(100) NOT NULL,
    buy_price NUMERIC(12, 2) NOT NULL DEFAULT 0,
    sell_price NUMERIC(12, 2) NOT NULL DEFAULT 0,
    stock INT NOT NULL DEFAULT 0,
    min_stock INT NOT NULL DEFAULT 5,
    unit VARCHAR(50) DEFAULT 'pcs',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. TRANSACTIONS TABLE
CREATE TABLE IF NOT EXISTS public.transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_no VARCHAR(50) NOT NULL UNIQUE,
    date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    subtotal NUMERIC(12, 2) NOT NULL DEFAULT 0,
    discount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    tax NUMERIC(12, 2) NOT NULL DEFAULT 0,
    total NUMERIC(12, 2) NOT NULL DEFAULT 0,
    pay_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    change_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    payment_method VARCHAR(50) NOT NULL DEFAULT 'Tunai',
    status VARCHAR(20) NOT NULL DEFAULT 'SELESAI',
    sync_status VARCHAR(20) NOT NULL DEFAULT 'TERSYNC',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. TRANSACTION ITEMS TABLE
CREATE TABLE IF NOT EXISTS public.transaction_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT REFERENCES public.transactions(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    sku VARCHAR(50),
    name VARCHAR(255) NOT NULL,
    buy_price NUMERIC(12, 2) NOT NULL DEFAULT 0,
    sell_price NUMERIC(12, 2) NOT NULL DEFAULT 0,
    qty INT NOT NULL DEFAULT 1,
    subtotal NUMERIC(12, 2) NOT NULL DEFAULT 0
);

-- 5. SETTINGS TABLE
CREATE TABLE IF NOT EXISTS public.settings (
    key VARCHAR(100) PRIMARY KEY,
    value TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- INDEXES
CREATE INDEX IF NOT EXISTS idx_products_sku ON public.products(sku);
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products(category);
CREATE INDEX IF NOT EXISTS idx_transactions_receipt_no ON public.transactions(receipt_no);
CREATE INDEX IF NOT EXISTS idx_transactions_date ON public.transactions(date);
CREATE INDEX IF NOT EXISTS idx_transaction_items_tx_id ON public.transaction_items(transaction_id);

-- ENABLE RLS
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transaction_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

-- POLICIES
CREATE POLICY "Allow anon select categories" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Allow anon insert categories" ON public.categories FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anon update categories" ON public.categories FOR UPDATE USING (true);
CREATE POLICY "Allow anon delete categories" ON public.categories FOR DELETE USING (true);

CREATE POLICY "Allow anon select products" ON public.products FOR SELECT USING (true);
CREATE POLICY "Allow anon insert products" ON public.products FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anon update products" ON public.products FOR UPDATE USING (true);
CREATE POLICY "Allow anon delete products" ON public.products FOR DELETE USING (true);

CREATE POLICY "Allow anon select transactions" ON public.transactions FOR SELECT USING (true);
CREATE POLICY "Allow anon insert transactions" ON public.transactions FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anon update transactions" ON public.transactions FOR UPDATE USING (true);
CREATE POLICY "Allow anon delete transactions" ON public.transactions FOR DELETE USING (true);

CREATE POLICY "Allow anon select transaction_items" ON public.transaction_items FOR SELECT USING (true);
CREATE POLICY "Allow anon insert transaction_items" ON public.transaction_items FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anon update transaction_items" ON public.transaction_items FOR UPDATE USING (true);
CREATE POLICY "Allow anon delete transaction_items" ON public.transaction_items FOR DELETE USING (true);

CREATE POLICY "Allow anon select settings" ON public.settings FOR SELECT USING (true);
CREATE POLICY "Allow anon insert settings" ON public.settings FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anon update settings" ON public.settings FOR UPDATE USING (true);
